### ISSUE TITLE
Hinweis auf notwendigen Unterordner

### ISSUE THREAD

**Issue by neumo** [farOverNinethousand/networkDriveChecker#1]
Danke für das super Script!
Ich hatte nach der Accounterstellung direkt die Standardordner gelöscht. Das Script legt aber genau in einem dieser Ordner die Testdatei an. Das Script habe ich für mich modifiziert.
Du könntest ggf. auch den Root-Ordner verwenden oder einen kurzen Hinweis auf den notwendigen Unterordner einfügen.

**Comment by farOverNinethousand** [comment]
Hui mein erstes Issue und dann auch noch nettes Feedback - danke!
Ich werde die Tage schauen, dass ich das Script so ändere, dass man den Pfad oben über die Einstellungen selbst bestimmen kann.
Ich habe diesen Pfad als default genommen, da er bei jedem Bitrix User erstmal existiert.

Grüße

**Comment by farOverNinethousand** [comment]
Neue Version kommt demnächst ;)
Bitte gib Feedback, ob das so passt.

Grüße

**Comment by neumo** [comment]
Servus,
jawohl das funktioniert. Besten Dank.

cu
Michael

Am 05.09.2019 um 17:14 schrieb farOverNinethousand:

**Comment by farOverNinethousand** [comment]
Danke fürs Feedback!
EDIT
Nochmal zu deiner Frage:
Den root Ordner wollte ich nicht verwenden für den Fall, dass doch was schiefgeht - nun kann mans ja eh selbst entscheiden.

Grüße
