### ISSUE TITLE
"Sprungziel - login wurde nicht gefunden"

### ISSUE THREAD

**Issue by s0m3guy** [farOverNinethousand/networkDriveChecker#2]
Nachdem ich Domain, Username bzw. Mailadresse sowie Passwort eingestellt habe und dann starte, erhalte ich folgende Ausgabe beim Ausführen und danach wird keine Log Datei erstellt:

```
In 10 Sekunden geht's weiter
Ueberspringe 8 Sekunden 'waittime_seconds_before_start' Start-Wartezeit, da dies der erste Start ist und es fuer diesen bereits eine extra-Wartezeit gibt
Suche freien Laufwerksbuchstaben
Das Sprungziel - login wurde nicht gefunden.
```

Hatte zuerst im Passwort ein Sonderzeichen aber das auch escaped ohne Erfolg. Jetzt hat das aktuelle Passwort keine Sonderzeichen und gleicher Fehler.

**Comment by farOverNinethousand** [comment]
Sers,
da du eigene Projekte auf GitHub hast nehme ich an, dass du durch Eintragen der Accounts keine Syntaxfehler verursacht hast?
Welches OS verwendest du?
Wo (Ordner) wird das Script ausgeführt?
Hast du es als Admin gestartet?
Falls ja: Die neue Version 1.40 behebt ein Problem, das auftreten konnte, wenn man das Script als Admin gestartet hat -->Bitte damit nochmal testen

**Comment by farOverNinethousand** [comment]
Laut [Aussage eines MyDealz Users](https://www.mydealz.de/comments/permalink/28098646) behebt Version 1.40 das von dir gemeldete Problem.

**Comment by farOverNinethousand** [comment]
Kein Feedback , aber laut MyDealz User fixed --> Issue closed
