### ISSUE TITLE
Wo kann ich das Tool herunterladen?

### ISSUE THREAD

**Issue by o0Julia0o** [farOverNinethousand/networkDriveChecker#3]
hey, wo ist der Downloadlink?

**Comment by farOverNinethousand** [comment]
Das ist bei jeder Github Repository gleich. Hier eine beispielhafte Anleitung:
https://wiki.mobaledlib.de/anleitungen/spezial/download_github

**Comment by o0Julia0o** [comment]
Danke Dir! Ich kenne das nur, dass bei Releases etwas steht und man das dann so herunterladen kann. Finde ich auch die einfachere Variante(auf Nutzer-Seite). Wobei das mit dem Code>Zip herunterladen auch super easy geht.

**Comment by farOverNinethousand** [comment]
> 

Kein Thema.
Joa gebe ich dir recht, aber bei solchen "quick and dirty" script Projekten gibt es oft keine Releases.
Kommt u.a. drauf an, wie viel Zeit man als Project Maintainer investieren will.

**Comment by farOverNinethousand** [comment]
Ich hab soeben ein Release eingestellt.
